apiVersion: v1
kind: Service
metadata:
  name: apprentice
  namespace: world
spec:
  selector:
    app: apprentice
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
  type: ClusterIP
